baseURL = 'https://brian-strickland.com/'
languageCode = 'en-us'
title = 'Brian Strickland'
#theme = "PaperMod
[taxonomies]
  tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
