baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
#theme = "PaperMod
[taxonomies]
  tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true